name: Build Android APKS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Gradle and Build
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 8.5  # Yeh automatic gradlew generate kar dega background me

    - name: Build Child App APK
      run: gradle :child-app:assembleDebug --stacktrace

    - name: Build Parent App APK
      run: gradle :parent-app:assembleDebug --stacktrace

    - name: Upload Child APK
      uses: actions/upload-artifact@v4
      with:
        name: Child-App-Debug
        path: child-app/build/outputs/apk/debug/*.apk

    - name: Upload Parent APK
      uses: actions/upload-artifact@v4
      with:
        name: Parent-App-Debug
        path: parent-app/build/outputs/apk/debug/*.apk
